### ISSUE TITLE
2020.3.34 URP After building cant work

### ISSUE THREAD

**Issue by ksom11** [sienaiwun/TAA_Unity_URP#11]
![image](https://user-images.githubusercontent.com/87938578/188403249-c6703322-2e1a-46b0-98ca-38d3c1229048.png)

It runs normally in edit mode, but the above error will occur after building

**Comment by sienaiwun** [comment]
Maybe you didn't include the TAA shader in the build. You can do it manually by adding it in the "Edit > Project Settings > Graphics"

**Comment by ksom11** [comment]
> Maybe you didn't include the TAA shader in the build. You can do it manually by adding it in the "Edit > Project Settings > Graphics"

After doing this, everything works fine.
