### ISSUE TITLE
Doesn't work in URP 10.x

### ISSUE THREAD

**Issue by Aydindeveloper** [sienaiwun/TAA_Unity_URP#3]
Works great in 2019.4. but it doesn't work on 2020.x.x (URP 10 .x) versions. can also be Mobile supported?
unity 2019.4, galaxy s20, vulkan, black screen and crash

**Comment by anonymous0317** [comment]
same here it doesnt work in unity 2020.3 LTS tho.

here the error:
NullReferenceException: Object reference not set to an instance of an object
Naiwen.TAA.TAAFeature.AddRenderPasses (UnityEngine.Rendering.Universal.ScriptableRenderer renderer, UnityEngine.Rendering.Universal.RenderingData& renderingData) (at Library/PackageCache/com.xienaiwen.taa@16f5ad91eb/Runtime/TAAFeature.cs:34)
UnityEngine.Rendering.Universal.ScriptableRenderer.AddRenderPasses (UnityEngine.Rendering.Universal.RenderingData& renderingData) (at Library/PackageCache/com.unity.render-pipelines.universal@10.3.2/Runtime/ScriptableRenderer.cs:650)
UnityEngine.Rendering.Universal.ForwardRenderer.Setup (UnityEngine.Rendering.ScriptableRenderContext context, UnityEngine.Rendering.Universal.RenderingData& renderingData) (at Library/PackageCache/com.unity.render-pipelines.universal@10.3.2/Runtime/ForwardRenderer.cs:289)
UnityEngine.Rendering.Universal.UniversalRenderPipeline.RenderSingleCamera (UnityEngine.Rendering.ScriptableRenderContext context, UnityEngine.Rendering.Universal.CameraData cameraData, System.Boolean anyPostProcessingEnabled) (at Library/PackageCache/com.unity.render-pipelines.universal@10.3.2/Runtime/UniversalRenderPipeline.cs:381)
UnityEngine.Rendering.Universal.UniversalRenderPipeline.RenderCameraStack (UnityEngine.Rendering.ScriptableRenderContext context, UnityEngine.Camera baseCamera) (at Library/PackageCache/com.unity.render-pipelines.universal@10.3.2/Runtime/UniversalRenderPipeline.cs:513)
UnityEngine.Rendering.Universal.UniversalRenderPipeline.Render (UnityEngine.Rendering.ScriptableRenderContext renderContext, UnityEngine.Camera[] cameras) (at Library/PackageCache/com.unity.render-pipelines.universal@10.3.2/Runtime/UniversalRenderPipeline.cs:241)
UnityEngine.Rendering.RenderPipeline.InternalRender (UnityEngine.Rendering.ScriptableRenderContext context, UnityEngine.Camera[] cameras) (at <42a5878ce129403083acccf18e43363f>:0)
UnityEngine.Rendering.RenderPipelineManager.DoRenderLoop_Internal (UnityEngine.Rendering.RenderPipelineAsset pipe, System.IntPtr loopPtr, System.Collections.Generic.List`1[T] renderRequests, Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle safety) (at <42a5878ce129403083acccf18e43363f>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by sienaiwun** [comment]
fixed.
